version: '3.3'

services: # list of services composing your application
   db: # the service hosting your MySQL instance
     container_name: training-app-db
     image: mysql:5.7 # the image and tag docker will pull from docker hub
     ports:
      - "3306:3306"
     volumes: # this section allows you to configure persistence within multiple restarts
       - db_data:/var/lib/mysql
     restart: always # if the db crash somehow, restart it
     environment: # env variables, you usually set this to override existing ones
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: training-app
       MYSQL_USER: root
       MYSQL_PASSWORD: root
    

volumes:
    db_data: